feat: update setup scripts for 2026

diff --git a/src/scripts/global/bin/checkout-main b/src/scripts/global/bin/checkout-main
--- a/src/scripts/global/bin/checkout-main
+++ b/src/scripts/global/bin/checkout-main
@@ -2,34 +2,34 @@
 
 # Fail if there are unsaved changes
 if ! git diff-index --quiet HEAD --; then
-    echo "You have unsaved changes. Please commit or stash them first."
-    exit 1
+  echo "You have unsaved changes. Please commit or stash them first."
+  exit 1
 fi
 
 # Save the name of the current branch
 current_branch=$(git rev-parse --abbrev-ref HEAD)
 
 if [[ "$current_branch" = "main" || "$current_branch" = "master" ]]; then
-  echo "Error: You are already on branch $branch."
+  echo "Error: You are already on branch $current_branch."
   exit 1
 fi
 
 # Force checkout main or master depending on which one exists
 if git show-ref --verify --quiet refs/heads/main; then
-    git checkout -f main
+  git checkout -f main
 elif git show-ref --verify --quiet refs/heads/master; then
-    git checkout -f master
+  git checkout -f master
 else
-    echo "Neither main nor master branch exists."
-    exit 1
+  echo "Neither main nor master branch exists."
+  exit 1
 fi
 
 git pull
 
 # Delete the old branch
 if [ "$current_branch" != "main" ] && [ "$current_branch" != "master" ]; then
-    git branch -D "$current_branch"
+  git branch -D "$current_branch"
 else
-    echo "Cannot delete main or master branch."
-    exit 1
+  echo "Cannot delete main or master branch."
+  exit 1
 fi
